org.gradle.jvmargs=-Xmx3G
org.gradle.parallel=true

org.gradle.configuration-cache=true

minecraft_version=26.1.2
minecraft_version_range=[26.1,26.2)
fabric_minecraft_version_range=~26.1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT
neogradle_version=7.1.38
neo_version=26.1.2.95

mod_version=3.0.0+26.1.2
maven_group=com.asphyxiamywife.elytrapitchhelper
archives_base_name=elytrapitchhelper
mod_id=elytrapitchhelper
mod_name=Elytra Pitch Helper
mod_license=CC0-1.0

fabric_api_version=0.155.2+26.1.2
modmenu_version=18.0.0

junit_version=6.1.3
jazzer_version=0.30.0
jmh_version=1.37
gson_version=2.14.0
