org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=1.21.11
loader_version=0.18.4
loom_version=1.14-SNAPSHOT
parchment_version=2025.12.20

mod_version=2.1.0+1.21.11
maven_group=com.asphyxiamywife.elytrapitchhelper
archives_base_name=elytrapitchhelper

fabric_api_version=0.141.1+1.21.11
modmenu_version=16.0.0-rc.1

trinkets_version=3.11.1-1.21.11
cca_version=7.1.0-beta.1
