org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

org.gradle.configuration-cache=false

minecraft_version=26.3-snapshot-1
loader_version=0.19.3
loom_version=1.17-SNAPSHOT

mod_version=2.1.0+26.3
maven_group=com.asphyxiamywife.elytrapitchhelper
archives_base_name=elytrapitchhelper

fabric_api_version=0.153.1+26.3
modmenu_version=20.0.0-beta.4

trinkets_version=4.1.0-beta.2+26.2
