modLoader="javafml"
loaderVersion="[1,)"
license="${mod_license}"
issueTrackerURL="https://github.com/asphyxiamywife/ElytraPitchHelper/issues"

[[mods]]
modId="${mod_id}"
version="${mod_version}"
displayName="${mod_name}"
displayTest="IGNORE_SERVER_VERSION"
displayURL="https://modrinth.com/mod/elytrapitchhelper"
logoFile="assets/elytrapitchhelper/icon.png"
authors="asphyxiamywife"
description='''Shows pitch and relative height guides for energy-sustaining Elytra flight.'''

[[mixins]]
config="elytrapitchhelper.mixins.json"

[[dependencies.${mod_id}]]
modId="neoforge"
type="required"
versionRange="[${neo_version},)"
ordering="NONE"
side="CLIENT"

[[dependencies.${mod_id}]]
modId="minecraft"
type="required"
versionRange="${minecraft_version_range}"
ordering="NONE"
side="CLIENT"
